Add option to disable the platform locale
sindresorhus/camelcase pull request #92
Opened 2021-12-19 16:37 UTC by jhnns

As discussed in https://github.com/sindresorhus/camelcase-keys/issues/81

2021-12-19 16:38 UTC, jhnns commented on index.js
> +		input = toLowerCase(input);
I think this fixes a bug "by accident" where the locale hasn't been applied previously.

2021-12-19 16:40 UTC, jhnns commented on test.js
> +/* eslint-enable no-extend-native */
I tried to separate this mocking setup from the rest of the test. I'm not sure if you agree with this style of mocking String.prototype functions. Another solution would be to spin up a separate Node process with `tr-TR` as locale but I thought that would be a bigger change.

2021-12-19 23:08 UTC, sindresorhus requested changes

2021-12-19 23:08 UTC, sindresorhus commented on readme.md
> +//=> 'loremIpsum'
I don't think these additions are needed. It's enough to document it at the API docs for the option.

2021-12-19 23:08 UTC, sindresorhus commented
You also need to update index.d.ts

2021-12-20 11:06 UTC, jhnns commented
I've updated the PR, ready to be reviewed again :)

2022-01-01 20:28 UTC, merged