Add target option
sindresorhus/camelcase pull request #93
Opened 2022-02-12 19:19 UTC by FullMoon04

I wanted to convert it to:
`camelCase(foo_bar.1)` => `fooBar.1`

At present, it will be converted to `fooBar1`.
That's why we implemented the target option.

2022-02-14 18:07 UTC, sindresorhus commented
I think it would make more sense to have a `preserveCharacters` option which would accept an array of characters.

2022-02-15 21:54 UTC, FullMoon04 commented
Thank you for your review. I fixed it.

2022-02-16 08:52 UTC, sindresorhus requested changes

2022-02-16 08:52 UTC, sindresorhus commented on index.js
> +		}
This can be done much simpler. There should also be validation for unsupported characters.

2022-02-16 08:52 UTC, sindresorhus commented on index.js
> +		regString = '[';
Don't use abbreviations.

2022-02-16 08:52 UTC, sindresorhus commented on readme.md
> +Type: `string[]`\
```suggestion
Type: `string[]`
```

2022-02-16 08:52 UTC, sindresorhus commented on readme.md
> +Preserve the given characters. The characters that can be specified are '_', '.', '-', ' ' or a combination thereof.
```suggestion
Preserve the given characters. The characters that can be specified are `_`, `.`, `-`, ` ` *(space)* or a combination thereof.

```

2022-02-16 08:52 UTC, sindresorhus commented on readme.md
> +```
You also need to update index.d.ts

2022-12-10 20:05 UTC, closed without merging